let mydate = new Date()
console.log(mydate.toLocaleString())
console.log(mydate.toString())
console.log(mydate.toDateString())
console.log(mydate.getDate())
console.log(mydate.getFullYear())
console.log(mydate.getTime())
let myCreatedDate = new Date(2023,10,19)
console.log(myCreatedDate.toLocaleString())
let date =  Date.now()
console.log(date)
